const Pl_SetPtn = 1; 
let Nupu_PlayerDash_Update = Game_Interpreter.prototype.NUpdate;
Game_Interpreter.prototype.NUpdate = function () {
    Nupu_PlayerDash_Update.call(this);
    if (!$gameSystem._SittingFlg) {
        if ($gamePlayer.isMoving() && $gamePlayer._walkAnime) {
            $gamePlayer._SetPtn = -1;
            if ($gamePlayer.isDashing() || $gamePlayer._moveSpeed >= 5) {
                if ($gamePlayer._characterIndex != 2) {
                    this.SetPlayerImg($gamePlayer._characterName, 2);
                }
            } else {
                if ($gamePlayer._characterIndex != 1) { 
                    if (b初期キャラ更新スキップFlg) {
                        b初期キャラ更新スキップFlg = false;
                        return;
                    }
                    this.SetPlayerImg($gamePlayer._characterName, 1);
                }
            }
        } else {
            if ($gamePlayer._characterIndex != 0) { 
                $gamePlayer._SetPtn = Pl_SetPtn; 
                this.SetPlayerImg($gamePlayer._characterName, 0);
            }
        }
    }
};
