Game_Interpreter.prototype.PL_DoorTateCk = function () {
    if (this.character(0) == undefined || this.character(-1) == undefined) return;
    if (Math.abs(this.character(0)._realX - this.character(-1)._realX) > 0.49) {
        console.log("ドア：イベントスキップ");
        this._index = this._list.length; 
    } else {
        if (this.character(0)._realY > this.character(-1)._realY) {
            this.character(-1)._direction = 2; 
        } else {
            this.character(-1)._direction = 8; 
        }
    }
};
let EventOnePlayDataArr = [];
Game_Interpreter.prototype.EventOnePlayCheck = function () {
    if (this.character(0).onePlayFlgs == undefined) this.character(0).onePlayFlgs = [];
    for (let i = 0; i < EventOnePlayDataArr.length; i++) {
        if (EventOnePlayDataArr[i] == this.character(0)._eventId) {
            return false; 
        }
    }
    EventOnePlayDataArr.push(this.character(0)._eventId);
    return true; 
}
let EventOnePlayDataArr_reserveTransfer = Game_Player.prototype.reserveTransfer;
Game_Player.prototype.reserveTransfer = function (mapId, x, y, d, fadeType) {
    EventOnePlayDataArr_reserveTransfer.call(this, mapId, x, y, d, fadeType);
    EventOnePlayDataArr = []; 
};
let SANFollowerDir固定 = false;
let SANFollowerDirection = 0;
let V隊列向き固定_ON = function (directionNo) {
    SANFollowerDir固定 = true;
    SANFollowerDirection = directionNo;
}
let V隊列向き固定_OFF = function () {
    SANFollowerDir固定 = false;
}
Game_Interpreter.prototype.Follower集合 = function () {
    for (let i = 0; i < $gamePlayer.followers()._data.length; i++) {
        $gamePlayer.followers()._data[i]._x = $gamePlayer._x;
        $gamePlayer.followers()._data[i]._y = $gamePlayer._y;
        $gamePlayer.followers()._data[i]._realX = $gamePlayer._realX;
        $gamePlayer.followers()._data[i]._realY = $gamePlayer._realY;
    }
}
